// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpkfOBB_WzVOu8c6uC-TeiUNHF1XETY4w',
    appId: '1:799208153346:web:55e80d05fc16049de0a21b',
    messagingSenderId: '799208153346',
    projectId: 'keithel-app',
    authDomain: 'keithel-app.firebaseapp.com',
    storageBucket: 'keithel-app.appspot.com',
    measurementId: 'G-2SC58FDB0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOQMyPSuSL8ENzJ8-6sWuRkHAAClQvUBc',
    appId: '1:799208153346:android:85ad1b4249292b74e0a21b',
    messagingSenderId: '799208153346',
    projectId: 'keithel-app',
    storageBucket: 'keithel-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZBKLEE0BzRzS03xkGcth8JjlaViVREik',
    appId: '1:799208153346:ios:0ccbc330c00bfdb9e0a21b',
    messagingSenderId: '799208153346',
    projectId: 'keithel-app',
    storageBucket: 'keithel-app.appspot.com',
    iosClientId: '799208153346-v7cbnvjg3vga431ob2rlifd940t35o8g.apps.googleusercontent.com',
    iosBundleId: 'com.example.keithel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZBKLEE0BzRzS03xkGcth8JjlaViVREik',
    appId: '1:799208153346:ios:0ccbc330c00bfdb9e0a21b',
    messagingSenderId: '799208153346',
    projectId: 'keithel-app',
    storageBucket: 'keithel-app.appspot.com',
    iosClientId: '799208153346-v7cbnvjg3vga431ob2rlifd940t35o8g.apps.googleusercontent.com',
    iosBundleId: 'com.example.keithel',
  );
}
